name: Tester

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install-OS-Dependencies
      run: sudo apt install python3 && sudo apt install python3-pip
    - name: Install-Python-Dependencies
      run: python3 -m pip install -r requirements.txt
    - name: Testing-Source
      run: python3 tests/tester.py
